fix: fixing no services edge case

diff --git a/.github/workflows/terraform_deploy.yaml b/.github/workflows/terraform_deploy.yaml
--- a/.github/workflows/terraform_deploy.yaml
+++ b/.github/workflows/terraform_deploy.yaml
@@ -80,7 +80,7 @@ jobs:
           npm run buildServiceManifest -- --servicesRoot=../../services
           echo "### Services Manifest" >> $GITHUB_STEP_SUMMARY
           echo '```yaml' >> $GITHUB_STEP_SUMMARY
-          cat ../../services/services-manifest.yaml >> $GITHUB_STEP_SUMMARY
+          cat ../../services/services-manifest.yaml >> $GITHUB_STEP_SUMMARY || echo "error" >> $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
           echo "### :warning: Missing env vars" >> $GITHUB_STEP_SUMMARY
           grep missing ../../services/services-manifest.yaml >> $GITHUB_STEP_SUMMARY
